### ISSUE TITLE
404s when clicking panels on overview page

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-monitoring#20] opened 2023-04-14 19:14 UTC
On the `1.0.0` or back on 4a5da0d00e24fd1e92f39db381127a4dd7780d9a I get 404s when I click on panels. Here's a video of me clicking panels and then going back and clicking on others:

https://user-images.githubusercontent.com/8253488/232135795-afc51190-d041-4f91-b7ee-1bb32d25ade5.mp4

**Comment by jkuester** [comment] 2023-04-17 13:54
I can see the same behavior.  Though it is worth noting that if I ctrl-click the link to open the panel in a new tab, it works fine.... :shrug:

**Comment by jkuester** [comment] 2023-04-21 18:01
I have determined this behavior started occurring as of this commit https://github.com/medic/cht-monitoring/commit/10eb5a431cda191bd58ba1e8d985980c0a08bf23

**Comment by jkuester** [comment] 2023-04-21 18:09
So, not sure how this worked before (probably has something to do with the old urls containing full URLs as a parameter or something). But, apparently the true cause behind the issue is how I formatted the internal links as starting with `./` instead of just `/`.  Related issue: https://github.com/grafana/grafana/issues/38612

I will work on a PR to fix this issue.

**Comment by jkuester** [comment] 2023-04-24 21:41
@tatilepizs this was the issue I forgot to get QA on before merging [the PR](https://github.com/medic/cht-monitoring/pull/25)!  Should be able to just test this from `main`.  

The behavior here is simple.  In `1.0.x`, if you click on the data in the panels on the "Overview" dashboard, if will take you to a new screen with a 404 error (but it works for some reason if you open the same link in a new tab).  Now, in `main`, you should be able to click on data from any of the panels in the "Overview" dashboard and see it open a new panel from the "Details" dashboard with the proper data.

**Comment by tatilepizs** [comment] 2023-04-26 17:26
It is working as expected, I didn't see any 404 error 🎉 

---

Move it to `Done` since it was already merged

**Closed** 2023-04-26 18:32 UTC
